### ISSUE TITLE
the p is not updated?

### ISSUE THREAD

**Issue by ry-jojo** [AvivSham/auxinash#1]
Hi there, thanks for sharing the codebase. 
I am confused about the implementation of AuxiNash. Where can I find the task preference vector p update after the initialization? https://github.com/AvivSham/auxinash/blob/f97bbd1817659ff58cf85c9d79ed3f60b3a460ce/methods/weight_methods.py#L321

**Comment by AvivSham** [comment]
Hi @ry-jojo 
Thank you for your interest in our work. The parameters `p` are updated using the meta optimizer after hyper grads calculation, please check the following code snip:
https://github.com/AvivSham/auxinash/blob/f97bbd1817659ff58cf85c9d79ed3f60b3a460ce/implicit_diff/optim.py
