### ISSUE TITLE
Why model is wrapped to be tuple in nyuv2/trainer.py line 37

### ISSUE THREAD

**Issue by jagdeeppani** [AvivSham/auxinash#2]
The code is resulting error on line 38 (model = model.to(device)), with, AttributeError: 'tuple' object has no attribute 'to'. This is a valid error. Just unwrapping, and making model = SegNet() enables the code to run smoothly. 

My question is, why model is wrapped to be a tuple. Any requirements down the line?

https://github.com/AvivSham/auxinash/blob/f97bbd1817659ff58cf85c9d79ed3f60b3a460ce/experiments/nyuv2/trainer.py#L37

**Comment by AvivSham** [comment]
Thank you for spotting this issue.
This is a typo mistake, I fixed it.
